### ISSUE TITLE
Minimega stderr/stdout in docker-compose logs

### ISSUE THREAD

**Issue by glattercj** [activeshadow/minimega#23] opened 2020-09-29 21:08 UTC
Since minimega is running as a systemd service inside a container, the only current way to get the minimega logs is to run

```bash
docker exec -it minimega journalctl -fu minimega
```

Ideally we could see the stdout/stderr from the host using `docker-compose logs -f`

**Comment by activeshadow** [comment] 2020-09-29 22:42
I don't think there's any way around this. We're bastardizing the minimega container by using an actual init system to run both OpenVSwitch and minimega in the same container (big no no!). By design, Docker grabs STDOUT/STDERR from PID 1 to show as logs via `docker logs`.

One option would be to create an alias like `mm-logs` that runs `journalctl -fu minimega` in the container.

**Comment by activeshadow** [comment] 2020-10-08 18:32
@glattercj you OK with me closing this, or do you want to discuss it more?

**Comment by glattercj** [comment] 2020-10-09 01:07
I'm good, thanks

**Closed** 2020-10-19 18:21 UTC
