### ISSUE TITLE
Testing Notes

### ISSUE THREAD

**Issue by glattercj** [activeshadow/minimega#10] opened 2020-07-17 20:20 UTC
# Testing notes

## phenix config ...
- [x] `delete Topology/helloworld`
  - it's not clear in help that "Topology/" is needed
- [x] `edit Topology/helloworld`
  - it's not clear in help that "Topology/" is needed

## phenix experiment ...
- [x] `create ...`
  - add checkmark or X next to apps depending on if they were applied or not (not found?)
- [x] `create --help`
  - fix 'optional' parameters (only -t is required)
- [x] `create -t foo -s bar`
  - "must provider experiment name" --> this isn't in the help
- [x] `start --dry-run test`
  - don't mark experiment as started if it's just a dry-run (if you attempt to start it for real after a dry-run, it says "already started")
- [x] `start helloworld`
  - better error message for user?

      ```bash
      getting experiment helloworld from store: getting config: key helloworld does not exist in bucket Experiment
      ```
- [x] `start/stop all`
  - keyword "all" doesn't exist anymore
- [x] `apps`
  - if no apps, empty results show twice in output

      ```bash
      Apps: none


      Apps:
      ```

## phenix vm ...
- [x] `info foo`
  - optionally show more than just "host, name, running, disk, interfaces, uptime"
  - compare to current 'phenix vm info ...'

      ```bash
      {'auto_assigned': None,
      'cdrom': None,
      'deploy_type': 'kvm',
      'disk': 'foo.qc2',
      'dnb': False,
      'host': None,
      'interfaces': '172.16.1.2',
      'mem': 8192,
      'metadata': "{'foo': 'bar', 'endpoint': "
                  "'udp://*;239.0.0.1:40000'}",
      'name': 'foobar',
      'os_type': 'windows',
      'snapshot': True,
      'vcpus': 4}
      ```

## phenix vlan ...
- [x] `alias`
  - doesn't show correct ID when exp is running
- [x] `range`
  - doesn't show correct range when exp is running

## phenix image ...
- [x] `create -h`
  - USAGE says "command options" and "flags", but there are only OPTIONS
- [x] `create ...`
  - unclear that full paths are needed for overlays/scripts
- [x] `create ...`
  - success message? Same for 'exp/cfg create ...'?
- [x] `list -h`
  - USAGE says "command options" and "arguments", but there are only OPTIONS
- [x] `list`
  - default show scripts, optionally show format, compressed, mirror
- [x] `update`
  - doesn't exist anymore; do we need this after editing e.g. script?
- [x] `build -v vvv ...`
  - this is confusing; if arg is needed after -v, maybe make it a value or 'low/med/high' rather than more 'v's
  - or allow '-v', '-vv', '-vvv' as flags (no arg)
- [x] `build ...`
  - list prereqs somewhere (i.e. vmdb2 needs to be on path etc.)
- [x] `build ... -r`
  - --ramdisk option doesn't exist anymore; **this is needed**
- [x] `build ... -c`
  - verify rootfs-tarball option creates only tar, not tgz
- [x] `build ... -o`
  - specify output location doesn't exist anymore
  - having a default output path of **/phenix/images** is *DANGEROUS* since we might overwrite an existing image.

      - vmdb2 adds the .qc2 extension as part of its teardown:

         ```bash
         Exec: ['qemu-img', 'convert', '-p', '-c', '-O', 'qcow2', '/phenix/images/foo', '/phenix/images/foo.qc2']
         ```
  - it's also storing the rootfs-tarball and vmdb config files in **/phenix/images**, which is also *DANGEROUS* since people may share **/phenix/images** across a cluster
  - compare to current behavior: write everything to CWD by default, but allow the user to specify an output directory if they want.

## Help
- [x] in several subcommands (`phenix vm net connect`) the global options (--help and --version) don't do anything
- [x] '--help and --version' are inconsistent (sometimes 'help, h' is a command, and sometimes it's an OPTION

## Misc
- [x] wherever needed, make sure providing an exp name or vm name or \<insert noun\> name is in the help
- [x] experiment vs host apps (do we need both? Just use labels?)
- [x] add example for app status (what's the standard way to do it?)

**Comment by activeshadow** [comment] 2020-07-17 23:59
Hey @glattercj thanks for taking the time to test and track your findings!

Regarding your notes about CLI args, help messages, and error messages, we started working on improving those in a separate branch last week, so we'll make sure to address your findings if we haven't already. We'll start marking the boxes above as complete as we confirm they've been fixed.

We'll post additional updates/questions here (or in an associated pull request) as we start to address and test some of the other issues you've mentioned here.

Thanks again!

**Comment by dnkcom** [comment] 2020-07-21 19:05
Hi @glattercj, for `vm info` do you want all the info that is in current `phenix vm info` or a portion of those items? If the latter, which items?

Once a couple branches are merged, I will confirm the remaining items above are confirmed. Many of them I caught in testing and should be addressed.

**Comment by glattercj** [comment] 2020-08-03 18:26
@dnkcom For `vm info`, table format is fine. For contents, it should at least include `disk`, `host`, `interfaces`, `mem`, `vcpus`, `name`, `os_type`, and `metadata`. If they could be optionally applied as filters (like `.columns x,y,z` in mini cli), that would be a nice-to-have.

**Comment by dnkcom** [comment] 2020-09-03 22:26
We have held off adding Metadata to `vm info`.

**Comment by activeshadow** [comment] 2020-09-04 15:39
@glattercj 

# Experiment vs. Host Apps

We need both, because we need a way to associate app metadata with a specific host without polluting the topology with the metadata. If we simply used topology labels, we'd have to put scenario-specific metadata in the topology definition for each host.

# Example of App Status in Experiment Config Status

During the app `config` and `pre-start` stages, user apps are able to make modifications to the experiment config spec. During the app `post-start` and `cleanup` stages, user apps are able to make modifications to the experiment config status, and more specifically the `status.apps[app_name]` portion of the experiment config status. The value of this portion of the status can be anything the user app wants it to be (ie. a simple string/int/float, an array of values, a dictionary, etc). The point of this portion of the status is for the user app to be able to specify whatever it wants about what it did to the experiment after the experiment was running.

As a contrived example, say there exists a `c2` user app that is part of an experiment scenario, and as part of the `post-start` stage this app makes calls to minimega to schedule actions on VMs using `minimega cc`. An example experiment config status for this app might look like the following:

```
status:
  apps:
    c2:
      vm-1:
      - sent file x
      - exec file x
      - recv file z
```

Now, to create such a status from the `c2` app, let's assume the app is written in Python. Apps are provided a JSON string over STDIN representing the experiment, which includes `metadata, spec, and status` top-level keys. Apps are expected to provide an updated version of the JSON string over STDOUT once completed. So in this case, a simplistic Python user app might look like the following:

```
import json, sys


def eprint(*args):
    print(*args, file=sys.stderr)


def main() :
    if len(sys.argv) != 2:
        eprint("must pass exactly one argument on the command line")
        sys.exit(1)

    raw = sys.stdin.read()

    if sys.argv[1] != 'post-start':
        print(raw)
        sys.exit(0)

    exp    = json.loads(raw)
    spec   = exp['spec]
    status = exp['status']

    app_status = {}

    for n in spec['topology']['nodes']:
        hostname = n['general']['hostname']
        # run some commands here for minimega cc for this node
        app_status[hostname] = [
            'sent file x',
            'exec file x',
            'recv file z',
        ]

    # This assumes the name of this user app is `c2`. The main phenix
    # app will ensure `exp['status']['apps']` exists prior to shelling
    # out to the user app.
    exp['status']['apps']['c2'] = app_status

    print(json.dumps(exp))
```

**Comment by activeshadow** [comment] 2020-09-04 20:20
This is all done! Yay!

**Closed by activeshadow** 2020-09-04 20:20 UTC
